### ISSUE TITLE
OpenSSD_BRAM_4L

### ISSUE THREAD

**Issue by vutacuong** [giuseppedongiovanni/nvme_comp_storage#1]
Hello.
I am very interested in your project. 
I have downloaded and run the project on motherboards zc706, and an error appears:

The oldest data was removed. Continue...
 virtualBlock 4043 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4044 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4045 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4046 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4047 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4048 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4049 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4050 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4051 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4052 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4053 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4054 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4055 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4056 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4057 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4058 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4059 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4060 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4061 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4062 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4063 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4064 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4065 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4066 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4067 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4068 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4069 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4070 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4071 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4072 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4073 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4074 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4075 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4076 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4077 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4078 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4079 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4080 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4081 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4082 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4083 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4084 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4085 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4086 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4087 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4088 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4089 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4090 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4091 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4092 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4093 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4094 is bad block 
No reserved block - Ch 0 Way 0 virtualBlock 4095 is bad block 
Bad block remapping end
assertion "!"[WARNING] There is no free block [WARNING]"" failed: file "../src/address_translation.c", line 251, function: InitCurrentBlockOfDieMap

Please help me to fix this.

Thank you for your time.

**Comment by giuseppedongiovanni** [comment]
Hi, thanks for the interest and sorry for the absence of documentation. I know about this problem, but it was solved in all the version that are present in the repository, so I can't really figure out why it is happening. What I can suggest for the moment, without knowing anything, is to try with other version of the project such as the OpenSSD_AXI_4L, follow the documentation of OpenSSD for the startup and see what happens. If you prefer, you can leave me your email so I can help you better.

**Comment by vutacuong** [comment]
Hi, thanks for your response.
I tried with all version of your project, and  this error still occurs.
This my email: vutacuong109@gmail.com.
Can you send me some documentation about your project and explain about that error
